name: test

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@master
        with:
          key: v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          path: node_modules
      - run: docker-compose up -d
      - run: sleep 20
      - run: yarn install
      - run: yarn tsc
      - run: yarn test


